language: php
sudo: required
dist: trusty

php:
  - '7.2'

branches:
  only:
    - dev

before_install:
  - mysql -e 'CREATE DATABASE dbp;'
  - mysql -e 'CREATE DATABASE sophia;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - npm install
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="4"